# .streamlit/secrets.toml

# Coloque sua NOVA chave do Gemini aqui
GOOGLE_API_KEY = "AIzaSyBIBWfXy9Bq56WnWOKYCE1F9PfjQChuGcw"

# Suas credenciais do Firebase (para o frontend)
[firebase_config]
apiKey = "AIzaSyAuRxH97q5d7gSRf723hrUjyV-tjmg3m-M"
authDomain = "max-marketing-total.firebaseapp.com"
projectId = "max-marketing-total"
storageBucket = "max-marketing-total.firebasestorage.app"
messagingSenderId = "442279100976"
appId = "1:442279100976:web:f53a9eacea9a14324f63f5"
measurementId = "G-206VHFW8MG"

# Sua conta de serviço (para o backend)
# Copie os valores do NOVO arquivo JSON que você baixou
[gcp_service_account]
type = "service_account"
project_id = "max-marketing-total"
private_key_id = "56cc53d2e8c5700cda296dc19a9688e73d0fff60"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCzj04QCa2fxKaG\nLNsPY2RQc6IUYUFHJQ++stJlUuN/PcXTfxrKMgRZpbFRqpS+HGl7CkjlMOTx8TCb\n4cfBywPZCZeOGWb0v7pTGXItLRTtuNVstDnaBr8WOQyUbWvzaw2Wqe2QkBiDUdmb\nV2l6PgUbSTg0RdlV9l8nEnJT82zPIHsBBq8McqNDlGfsfjCOrAqtvhCTNbQEn1Tx\n6RgaiY8kdFVkwpn2S+yvwJLyo2eFxvv4ZP2J5ckeuCOAozG7ims2iomCwtYRDkzH\n4wesksveT5laKadDwR42a9WRfu7ig5PGv4ux16JBt53GTpTy+RWxdblDirbZs6WF\nu5WQ0RqhAgMBAAECggEAG24DW1DXLKZyV+HnTvj8fIvFkT5wJemj95pCqMbaSPhL\nTa1HjubIIle8+EBKO6aEeI7QJu7qsokJR27cwJ5+RnwAIm1//FiDoqkq93rBDTWk\nqNf5VHSeYUsywEPc71EFwOPRjjls/TaWOvRGAS4TQqFTTCz1b/vUelgHjgqMLzHB\nMvPdgr04BuTjJ5x8yv2XPr/sSPqlZTtF9OXbSICNeius2SEfXCXIxuhkCAPc4Yqd\nwqE1GnQu0V8TWWt6NmIYXT61KmV2JOu9sZcfgOwMAU/RmXHr6N10RFkIYS3r2J6f\nU40jZSd691Nk0HhITJNuLwnAGkuX4eKLK+fxHP5NTwKBgQD7WSjzImHsqzzUs1x6\nzp0hWiwcja5KCTlnr3+WaASsjCAPN0wh9a+odP7Sf9k1M9RM0vu4zwDScEStlUsb\nd/0qm9xvqHa+PAa6/VdEJidaA5ImwUKTrk/6mKp0TBVxkHqVEMURnK1xYaBFNQBs\n9rjOo4pBFfFzCx7amb2mlPOarwKBgQC24gZalwgdX4oJk6KZ2m/yIHaHIbjouc4l\n0TP+2zF8t1EdnWYXUCThHOypJ+9DiBS8ifFcrDww090PwIsYz8xxmgAoyIW9r59q\n4801lODq/GiBIJ43gMwT22X/ZO7TpU58A94LM3tf3cSSA/LWM5EzrDQWGdckI2ne\n+HEg6X6zrwKBgGTX0twpsUw5L8DO7Y3AE77r5MLX/VNq/AMjoHcB6M4psjsonn0J\ni550wkBGVylHUCg6hhARzWyg6o0SVv4AWCyeOAT8fBe7EaA4QKjw/dzZjevKoiGK\nUEBkvA7I79mOdAAWqFp2mAfjeWAK8c7F9kPBzZhra2IS1iAyiqqpHEu1AoGBAJmq\ng4I844Gi1F7FoVu7UlLVeiKDcFaEQTY/eXwMe6F6evryVWUDX2mTnztnJcDNp/bf\nxWGECzNP4bCprXbUq8lMiBO8obvHxKDQ9o2uIerw2XKekLK8Uz3gHO0ixxYpETBd\nI4av5FuiANhb3wCi5b/QUxe68K4Z34yNnqjz6RVbAoGBAIjixWkczZLGOX5UbZWK\n6co/GIrqbGHY47T7k4SFMaUFSzMt1T/430dmp+i1+dgZn1jg47bonsgnagoDJPhb\nkFt4r7tJmA/QKRJaO89InKq5mesVYRJvnHUQoC2Q+ea6DQfUrIG6IE+tpUzBdGWP\nJdTtfQeQBiJWq5TX7wIlDasz\n-----END PRIVATE KEY-----\n"
client_email = "adm-max-marketing-total@max-marketing-total.iam.gserviceaccount.com"
client_id = "113376508265429822592"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/adm-max-marketing-total%40max-marketing-total.iam.gserviceaccount.com"
universe_domain = "googleapis.com"